name: ESLint Check

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
