name: Jest Tests

on:
  pull_request:
    branches: [main, dev]
    types: [opened, edited, closed, reopened]
  workflow_dispatch:
      
jobs:
  test:
    name: Run Jest
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run Jest
        run: npm test